import numpy as np
import pandas as pd


def compute_woe_iv(df: pd.DataFrame, feature: str, target: pd.Series, n_bins: int = 20) -> pd.DataFrame:
    """
    Compute Weight of Evidence (WoE) and Information Value (IV) for a single feature.

    WoE measures the strength of a feature in separating events (good customers)
    from non-events (bad customers) within each bin.
    IV measures the overall predictive power of the feature.

    Parameters:
        df      (pd.DataFrame): Input DataFrame containing the feature.
        feature (str)         : Name of the feature to compute WoE and IV for.
        target  (pd.Series)   : Binary target variable (1 = Good customer, 0 = Poor customer).
        n_bins  (int)         : Number of quantile bins for continuous features. Default is 10.

    Returns:
        stats_df (pd.DataFrame): DataFrame with WoE and IV values per bin, containing:
            - feature         : Feature name
            - bin             : Bin interval or category
            - events          : Count of good customers in bin
            - non_events      : Count of bad customers in bin
            - dist_events     : Distribution of good customers in bin
            - dist_non_events : Distribution of bad customers in bin
            - WoE             : Weight of Evidence for the bin
            - IV              : Information Value contribution of the bin
            - total_IV        : Total IV of the feature (same value repeated per row)
    """
    temp = df[[feature]].copy()
    temp['target'] = target.values

    # Features with few unique values are treated as categorical, otherwise bin into quantiles
    if df[feature].nunique() <= n_bins:
        temp['bin'] = df[feature].astype(str)
    else:
        temp['bin'] = pd.qcut(df[feature], q=n_bins, duplicates='drop')

    total_events = (temp['target'] == 1).sum()
    total_non_events = (temp['target'] == 0).sum()

    stats = []
    for bin_val, group in temp.groupby('bin'):
        events = (group['target'] == 1).sum()
        non_events = (group['target'] == 0).sum()

        # Clip to 0.5 minimum to avoid log(0) when a bin has no events or non-events
        dist_events = max(events, 0.5) / total_events
        dist_non_events = max(non_events, 0.5) / total_non_events

        woe = np.log(dist_events / dist_non_events)
        iv = (dist_events - dist_non_events) * woe

        stats.append({
            'feature': feature,
            'bin': bin_val,
            'events': events,
            'non_events': non_events,
            'dist_events': dist_events,
            'dist_non_events': dist_non_events,
            'WoE': woe,
            'IV': iv
        })

    stats_df = pd.DataFrame(stats)
    stats_df['total_IV'] = stats_df['IV'].sum()
    return stats_df


def apply_woe(df: pd.DataFrame, feature: str, woe_table: pd.DataFrame, n_bins: int = 20) -> pd.Series:
    """
    Apply a pre-fitted WoE table to replace feature values with their WoE scores.

    Parameters:
        df        (pd.DataFrame): Input DataFrame containing the feature to transform.
        feature   (str)         : Name of the feature to encode.
        woe_table (pd.DataFrame): WoE table generated by compute_woe_iv() for this feature.
        n_bins    (int)         : Number of bins used during fitting. Must match fit_woe(). Default is 10.

    Returns:
        woe_series (pd.Series): Series of WoE-encoded values for the feature.
                                Unseen bins (present in test but not in train) are filled with 0.
    """
    temp = df[[feature]].copy()

    # Replicate the same binning logic used during fitting
    if df[feature].nunique() <= n_bins:
        temp['bin'] = df[feature].astype(str)
    else:
        temp['bin'] = pd.qcut(df[feature], q=n_bins, duplicates='drop')

    # Map each bin to its corresponding WoE value
    bin_to_woe = woe_table.set_index('bin')['WoE'].to_dict()
    temp['WoE'] = temp['bin'].map(bin_to_woe)

    # Fill unseen bins (e.g. in test set) with neutral WoE value of 0
    temp['WoE'] = temp['WoE'].fillna(0)
    return temp['WoE']


def fit_woe(X_train: pd.DataFrame, y_train: pd.Series, features: list, n_bins: int = 20) -> tuple:
    """
    Fit WoE tables for all specified features using the training data.

    Iterates over each feature, computes its WoE/IV table, and aggregates
    IV values into a summary for feature selection purposes.

    Parameters:
        X_train  (pd.DataFrame): Training feature matrix.
        y_train  (pd.Series)   : Binary training target (1 = Good, 0 = Poor).
        features (list)        : List of feature names to encode.
        n_bins   (int)         : Number of quantile bins for continuous features. Default is 10.

    Returns:
        woe_tables (dict)         : Dictionary mapping each feature name to its WoE table (pd.DataFrame).
        iv_summary (pd.DataFrame) : DataFrame with total IV per feature, sorted descending.
    """
    woe_tables = {}
    iv_summary = {}

    for feature in features:
        table = compute_woe_iv(X_train, feature, y_train, n_bins)
        woe_tables[feature] = table
        iv_summary[feature] = table['total_IV'].iloc[0]

    iv_summary = pd.DataFrame.from_dict(
        iv_summary, orient='index', columns=['IV']
    ).sort_values('IV', ascending=False)

    return woe_tables, iv_summary


def transform_woe(X: pd.DataFrame, woe_tables: dict, features: list, n_bins: int = 20) -> pd.DataFrame:
    """
    Apply fitted WoE tables to transform a dataset (train or test).

    Each feature's raw values are replaced by their corresponding WoE scores
    using the tables learned during fit_woe().

    Parameters:
        X          (pd.DataFrame): Input feature matrix to transform.
        woe_tables (dict)        : Dictionary of WoE tables from fit_woe().
        features   (list)        : List of feature names to encode.
        n_bins     (int)         : Number of bins used during fitting. Must match fit_woe(). Default is 10.

    Returns:
        woe_df (pd.DataFrame): Transformed DataFrame where all feature values
                               are replaced by their WoE scores.
    """
    woe_df = X[features].copy()

    for feature in features:
        woe_df[feature] = apply_woe(X, feature, woe_tables[feature], n_bins)

    return woe_df


def get_woe_encoded_data(X_train: pd.DataFrame, y_train: pd.Series,
                         X_test: pd.DataFrame,  features: list) -> tuple:
    """
    Full WoE encoding pipeline for a 3-class credit scoring problem.

    Fits WoE tables using only Poor (0) and Good (2) customers from the training set,
    excluding Standard (1) customers to ensure clean signal. The learned tables are
    then applied to the full train and test sets, including Standard customers.

    Parameters:
        X_train  (pd.DataFrame): Training feature matrix (all 3 classes).
        y_train  (pd.Series)   : Training target with original classes (0=Poor, 1=Standard, 2=Good).
        X_test   (pd.DataFrame): Testing feature matrix (all 3 classes).
        features (list)        : List of feature names to encode.

    Returns:
        X_train_woe (pd.DataFrame): WoE-encoded training feature matrix.
        X_test_woe  (pd.DataFrame): WoE-encoded testing feature matrix.
        iv_summary  (pd.DataFrame): IV summary per feature sorted descending.
    """
    # Exclude Standard customers so WoE captures pure Poor vs Good distinction
    mask = y_train != 1
    X_filtered = X_train[mask]
    target_filtered = (y_train[mask] == 2).astype(int)  # Poor=0, Good=1

    # Fit WoE tables on Poor vs Good only
    woe_tables, iv_summary = fit_woe(X_filtered, target_filtered, features)

    # Apply learned tables to full datasets (Standard customers get interpolated WoE values)
    X_train_woe = transform_woe(X_train, woe_tables, features)
    X_test_woe = transform_woe(X_test,  woe_tables, features)

    return X_train_woe, X_test_woe, iv_summary
